window.FINANCE_REVIEW_DATA = {
  metadata: {
    bundleVersion: "m5-review-1",
    generatedAt: "2026-05-27",
    label: "M5 Review-Daten (Demo)",
    validation: "passed",
  },
  immobilien: [
    { immobilie_id: "IMM-001", bezeichnung: "DEMO Eigenheim", eigentumsanteile: [{ person_id: "PER-001", zaehler: 1, nenner: 2 }, { person_id: "PER-002", zaehler: 1, nenner: 2 }], status: "aktiv", quelle_hinweis: "DEMO" },
  ],
  darlehen: [
    { darlehen_id: "DAR-001", bezeichnung: "DEMO Hypothek", status: "aktiv", anfangsbetrag: "300000.00", anfangsdatum: "2020-01-31", zinssatz: "1.80", sollrate: "1000.00", rhythmus_einheit: "monat", rhythmus_intervall: 1, immobilie_id: "IMM-001", konto_id: "KTO-003", quelle_hinweis: "DEMO" },
  ],
  vermoegenswerte: [
    { vermoegenswert_id: "VMW-001", typ: "edelmetall", bezeichnung: "DEMO Gold", eigentumsanteile: [{ person_id: "PER-001", zaehler: 1, nenner: 1 }], status: "aktiv", quelle_hinweis: "DEMO" },
  ],
  zeitwerte: [
    { entitaet: "konto", entitaet_id: "KTO-001", feld: "kontostand", wert: "3500.00", standdatum: "2026-05-01", qualitaet: "belegt", quelle_hinweis: "DEMO" },
    { entitaet: "konto", entitaet_id: "KTO-006", feld: "depotwert", wert: "25000.00", standdatum: "2026-05-01", qualitaet: "geschaetzt", quelle_hinweis: "DEMO" },
    { entitaet: "immobilie", entitaet_id: "IMM-001", feld: "marktwert", wert: "450000.00", standdatum: "2026-01-01", qualitaet: "geschaetzt", quelle_hinweis: "DEMO" },
    { entitaet: "darlehen", entitaet_id: "DAR-001", feld: "restschuld", wert: "250000.00", standdatum: "2026-05-01", qualitaet: "belegt", quelle_hinweis: "DEMO" },
    { entitaet: "vermoegenswert", entitaet_id: "VMW-001", feld: "marktwert", wert: "8000.00", standdatum: "2026-04-01", qualitaet: "geschaetzt", quelle_hinweis: "DEMO" },
  ],
  personen: [
    { person_id: "PER-001", name: "Lars", status: "aktiv" },
    { person_id: "PER-002", name: "Katrin", status: "aktiv" },
  ],
  konten: [
    {
      konto_id: "KTO-001",
      name: "Girokonto Lars",
      kontotyp: "giro",
      kontoreferenz: "DE98...1175",
      inhaber_person_ids: ["PER-001"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-002",
      name: "Girokonto Katrin Deutsche Bank",
      kontotyp: "giro",
      inhaber_person_ids: ["PER-002"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-003",
      name: "Hauskonto Volksbank BraWo",
      kontotyp: "giro",
      inhaber_person_ids: ["PER-001"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-004",
      name: "Tagesgeld Lars Volkswagenbank",
      kontotyp: "tagesgeld",
      inhaber_person_ids: ["PER-001"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-005",
      name: "Tagesgeld Katrin Volkswagenbank",
      kontotyp: "tagesgeld",
      inhaber_person_ids: ["PER-002"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-006",
      name: "Trade Republic Lars",
      kontotyp: "depot",
      inhaber_person_ids: ["PER-001"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
    {
      konto_id: "KTO-007",
      name: "Gemeinsames Depot MLP",
      kontotyp: "depot",
      inhaber_person_ids: ["PER-001", "PER-002"],
      liquiditaetsrelevant: true,
      status: "aktiv",
    },
  ],
  kategorien: [
    { kategorie_id: "KAT-001", name: "Gehalt", typ: "einnahme", lebenshaltung_relevant: false, status: "aktiv" },
    { kategorie_id: "KAT-002", name: "Wohnen", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-003", name: "Lebensmittel", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-004", name: "Mobilitaet", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-005", name: "Versicherung", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-006", name: "Gesundheit", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-007", name: "Freizeit", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-008", name: "Kinder/Familie", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
    { kategorie_id: "KAT-009", name: "Steuern/Abgaben", typ: "ausgabe", lebenshaltung_relevant: false, status: "aktiv" },
    { kategorie_id: "KAT-010", name: "Sparen/Investieren", typ: "neutral", lebenshaltung_relevant: false, status: "aktiv" },
    { kategorie_id: "KAT-011", name: "Transfer", typ: "neutral", lebenshaltung_relevant: false, status: "aktiv" },
    { kategorie_id: "KAT-012", name: "Sonstiges / zu pruefen", typ: "ausgabe", lebenshaltung_relevant: true, status: "aktiv" },
  ],
  transaktionen: [
    {
      transaktion_id: "TXN-20260501-000001",
      dedupe_hash: "m1-demo-001",
      rohquelle: "data/demo/m1-demo-umsatz.csv",
      konto_id: "KTO-001",
      buchungsdatum: "2026-05-01",
      betrag: "3500.00",
      gegenpartei: "Arbeitgeber Demo",
      verwendungszweck: "Gehalt Mai Demo",
      kategorisierung_status: "bestaetigt",
      ist_transfer: false,
      kategorie_id: "KAT-001",
    },
    {
      transaktion_id: "TXN-20260503-000002",
      dedupe_hash: "m1-demo-002",
      rohquelle: "data/demo/m1-demo-umsatz.csv",
      konto_id: "KTO-001",
      buchungsdatum: "2026-05-03",
      betrag: "-82.45",
      gegenpartei: "Supermarkt Demo",
      verwendungszweck: "Wocheneinkauf Demo",
      kategorisierung_status: "bestaetigt",
      ist_transfer: false,
      kategorie_id: "KAT-003",
    },
    {
      transaktion_id: "TXN-20260505-000003",
      dedupe_hash: "m1-demo-003",
      rohquelle: "data/demo/m1-demo-umsatz.csv",
      konto_id: "KTO-001",
      buchungsdatum: "2026-05-05",
      betrag: "-500.00",
      gegenpartei: "Umbuchung Tagesgeld Demo",
      verwendungszweck: "Sparen Demo",
      kategorisierung_status: "bestaetigt",
      ist_transfer: true,
      kategorie_id: "KAT-011",
      transfer_id: "TRF-20260505-001",
    },
    {
      transaktion_id: "TXN-20260505-000004",
      dedupe_hash: "m1-demo-004",
      rohquelle: "data/demo/m1-demo-tagesgeld.csv",
      konto_id: "KTO-004",
      buchungsdatum: "2026-05-05",
      betrag: "500.00",
      gegenpartei: "Umbuchung Girokonto Demo",
      verwendungszweck: "Sparen Demo",
      kategorisierung_status: "bestaetigt",
      ist_transfer: true,
      kategorie_id: "KAT-011",
      transfer_id: "TRF-20260505-001",
    },
    {
      transaktion_id: "TXN-20260506-000005",
      dedupe_hash: "m1-demo-005",
      rohquelle: "data/demo/m1-demo-umsatz.csv",
      konto_id: "KTO-001",
      buchungsdatum: "2026-05-06",
      betrag: "-19.99",
      gegenpartei: "Unbekannt Demo",
      verwendungszweck: "Noch zu klaeren Demo",
      kategorisierung_status: "offen",
      ist_transfer: false,
    },
  ],
  transfers: [
    {
      transfer_id: "TRF-20260505-001",
      betrag: "500.00",
      typ: "intern",
      abgang_transaktion_id: "TXN-20260505-000003",
      zugang_transaktion_id: "TXN-20260505-000004",
    },
  ],
  checks: [
    {
      check_id: "CHK-M2-VALID-001",
      severity: "success",
      status: "bestaetigt",
      scope: "datenstand",
      title_key: "checks.validationPassed.title",
      detail_key: "checks.validationPassed.detail",
    },
    {
      check_id: "CHK-M2-CAT-001",
      severity: "review",
      status: "offen",
      scope: "transaktion",
      entity_id: "TXN-20260506-000005",
      title_key: "checks.categoryOpen.title",
      detail_key: "checks.categoryOpen.detail",
    },
    {
      check_id: "CHK-M2-REF-001",
      severity: "review",
      status: "offen",
      scope: "konto",
      entity_id: "KTO-002",
      title_key: "checks.accountReferenceMissing.title",
      detail_key: "checks.accountReferenceMissing.detail",
    },
    {
      check_id: "CHK-M2-REF-002",
      severity: "review",
      status: "offen",
      scope: "konto",
      entity_id: "KTO-003",
      title_key: "checks.accountReferenceMissing.title",
      detail_key: "checks.accountReferenceMissing.detail",
    },
    {
      check_id: "CHK-M2-REF-003",
      severity: "review",
      status: "offen",
      scope: "konto",
      entity_id: "KTO-004",
      title_key: "checks.accountReferenceMissing.title",
      detail_key: "checks.accountReferenceMissing.detail",
    },
    {
      check_id: "CHK-M2-REF-004",
      severity: "review",
      status: "offen",
      scope: "konto",
      entity_id: "KTO-005",
      title_key: "checks.accountReferenceMissing.title",
      detail_key: "checks.accountReferenceMissing.detail",
    },
  ],
  importfehler: [
    {
      fehler_id: "IMP-20260528-001",
      rohquelle: "data/inbox/error/volksbank-mai.csv",
      row: 7,
      reason: "konto_unbekannt",
      detail: "KTO-009 nicht in konten.json",
    },
  ],
  regelzahlungen: [
    { regelzahlung_id: "RZ-001", bezeichnung: "Gehalt Lars (Demo)", betrag: "3500.00", rhythmus_einheit: "monat", rhythmus_intervall: 1, anker_datum: "2026-01-30", status: "bestaetigt", kategorie_id: "KAT-001", erstellt_am: "2026-06-02", bemerkung: "Demo" },
    { regelzahlung_id: "RZ-002", bezeichnung: "Miete (Demo)", betrag: "-1200.00", rhythmus_einheit: "monat", rhythmus_intervall: 1, anker_datum: "2026-01-01", status: "bestaetigt", kategorie_id: "KAT-002", erstellt_am: "2026-06-02", bemerkung: "Demo" },
    { regelzahlung_id: "RZ-003", bezeichnung: "Handyvertrag (Demo)", betrag: "-29.99", rhythmus_einheit: "monat", rhythmus_intervall: 1, anker_datum: "2025-07-01", aktiv_bis: "2027-07-01", status: "vorgeschlagen", kategorie_id: "KAT-007", erstellt_am: "2026-06-02", bemerkung: "Demo, Vorschlag" },
  ],
};

window.FINANCE_REVIEW_DATA.transaktionen.push(
  ...[
    ["20260507", "000006", "KTO-001", "-42.80", "Baeckerei Demo", "Fruehstueck Demo", "KAT-003"],
    ["20260508", "000007", "KTO-002", "-64.20", "Drogerie Demo", "Haushalt Demo", "KAT-008"],
    ["20260509", "000008", "KTO-003", "-1200.00", "Darlehen Demo", "Rate Haus Demo", "KAT-002"],
    ["20260510", "000009", "KTO-001", "-38.90", "Tankstelle Demo", "Tanken Demo", "KAT-004"],
    ["20260511", "000010", "KTO-002", "-96.15", "Supermarkt Demo", "Wocheneinkauf Demo", "KAT-003"],
    ["20260512", "000011", "KTO-001", "-18.50", "Apotheke Demo", "Medizin Demo", "KAT-006"],
    ["20260513", "000012", "KTO-003", "-210.00", "Stadtwerke Demo", "Energie Demo", "KAT-002"],
    ["20260514", "000013", "KTO-001", "-47.30", "Restaurant Demo", "Abendessen Demo", "KAT-007"],
    ["20260515", "000014", "KTO-002", "1850.00", "Arbeitgeber Demo", "Gehalt Teil Demo", "KAT-001"],
    ["20260516", "000015", "KTO-004", "2.15", "Volkswagenbank Demo", "Zinsen Demo", "KAT-001"],
    ["20260517", "000016", "KTO-001", "-29.99", "Streaming Demo", "Abo Demo", "KAT-007"],
    ["20260518", "000017", "KTO-002", "-72.60", "Supermarkt Demo", "Wocheneinkauf Demo", "KAT-003"],
    ["20260519", "000018", "KTO-001", "-350.00", "Versicherung Demo", "Beitrag Demo", "KAT-005"],
    ["20260520", "000019", "KTO-003", "-89.40", "Baumarkt Demo", "Hausbedarf Demo", "KAT-002"],
    ["20260521", "000020", "KTO-001", "-15.00", "Parken Demo", "Parkticket Demo", "KAT-004"],
    ["20260522", "000021", "KTO-002", "-44.90", "Kinder Demo", "Schule Demo", "KAT-008"],
    ["20260523", "000022", "KTO-001", "-128.00", "Finanzamt Demo", "Steuern Demo", "KAT-009"],
    ["20260524", "000023", "KTO-005", "1.80", "Volkswagenbank Demo", "Zinsen Demo", "KAT-001"],
    ["20260525", "000024", "KTO-001", "-53.70", "Supermarkt Demo", "Wocheneinkauf Demo", "KAT-003"],
    ["20260526", "000025", "KTO-002", "-22.00", "Kino Demo", "Freizeit Demo", "KAT-007"],
    ["20260527", "000026", "KTO-001", "-500.00", "Sparplan Demo", "Investieren Demo", "KAT-010"],
    ["20260528", "000027", "KTO-002", "-31.45", "Drogerie Demo", "Haushalt Demo", "KAT-008"],
    ["20260529", "000028", "KTO-001", "-76.20", "Supermarkt Demo", "Wocheneinkauf Demo", "KAT-003"],
    ["20260530", "000029", "KTO-003", "-145.00", "Hausservice Demo", "Wartung Demo", "KAT-002"],
    ["20260531", "000030", "KTO-001", "-12.99", "App Store Demo", "Software Demo", "KAT-007"],
  ].map(([date, serial, kontoId, amount, counterparty, purpose, categoryId], index) => ({
    transaktion_id: `TXN-${date}-${serial}`,
    dedupe_hash: `m2-demo-${String(index + 6).padStart(3, "0")}`,
    rohquelle: "data/demo/m2-demo-umsatz.csv",
    konto_id: kontoId,
    buchungsdatum: `${date.slice(0, 4)}-${date.slice(4, 6)}-${date.slice(6, 8)}`,
    betrag: amount,
    gegenpartei: counterparty,
    verwendungszweck: purpose,
    kategorisierung_status: "bestaetigt",
    ist_transfer: false,
    kategorie_id: categoryId,
  })),
);
